language: go
jobs:
  include:
    - os: linux
      go: 1.14.x
      arch: amd64
    - os: linux
      go: 1.15.x
      arch: amd64
    - os: linux
      go: 1.15.x
      arch: arm64
    - os: windows
      go: 1.15.x
      arch: amd64
    - os: osx
      go: 1.15.x
      arch: amd64
go_import_path: github.com/vechain/thor
sudo: false
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y make; choco install -y mingw; export PATH=/c/tools/mingw64/bin:"$PATH"; fi
script:
  - make all test
