language: go
go_import_path: github.com/vechain/thor
sudo: false
matrix:
  include:
    - os: linux
      dist: trusty
      go: 1.12.x
    - os: osx
      go: 1.12.x
    - os: windows
      go: 1.12.x
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y make; choco install -y mingw; export PATH=/c/tools/mingw64/bin:"$PATH"; fi
install:
  - make dep
script:
  - make all test
